sudo: false

language: java
jdk:
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"

install:
    - TERM=dumb ./gradlew clean

script:
    - TERM=dumb ./gradlew assemble
